local Yutils = dofile("../src/Yutils.lua")

local bmp = Yutils.decode.create_bmp_reader("test.bmp")
print("File size: " .. bmp.file_size())
print("Width: " .. bmp.width())
print("Height: " .. bmp.height())
print("Depth: " .. bmp.bit_depth())
print("Data size: " .. bmp.data_size())
print("Row size: " .. bmp.row_size())
print("Rows go bottom-up: ", bmp.bottom_up())
print("Packed data:\n" .. Yutils.table.tostring(bmp.data_packed()))
print("Data text: " .. bmp.data_text())